"""create tenants table

Revision ID: 6e9fcbc2f174
Revises: 492e1a5750d1
Create Date: 2024-10-08 22:03:36.812736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e9fcbc2f174'
down_revision = '492e1a5750d1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
