"""i've modified constraint on payments table

Revision ID: d796e2901555
Revises: ae6e51ec03c7
Create Date: 2024-10-09 03:24:57.823459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd796e2901555'
down_revision = 'ae6e51ec03c7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
